<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.cafemanagement</groupId>
        <artifactId>CafeManagementSystem</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <artifactId>server-app</artifactId>
    <name>Cafe Management System - Server App</name>

    <properties>
        <mysql-connector.version>8.3.0</mysql-connector.version>
        <bcrypt.version>0.10.2</bcrypt.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.cafemanagement</groupId>
            <artifactId>shared</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>com.mysql</groupId>
            <artifactId>mysql-connector-j</artifactId>
            <version>${mysql-connector.version}</version>
        </dependency>
        <dependency>
            <groupId>at.favre.lib</groupId>
            <artifactId>bcrypt</artifactId>
            <version>${bcrypt.version}</version>
        </dependency>
    </dependencies>
</project>
